Repository Queryus/QGenie_app, pull requests merged in 2025-08, with the labels that each got.

#23 [FRT-48] AI 채팅 - 입출력
  electron.vite.config.ts
  package-lock.json
  package.json
  src/renderer/src/components/workspace/ai-chat-panel/ai-chat-panel.tsx
  src/renderer/src/components/workspace/ai-chat-panel/chat-input.tsx
  src/renderer/src/components/workspace/ai-chat-panel/chat-message.tsx
Labels: feature, frontend

#25 [FRT-54] AI 채팅 - 로딩 애니메이션
  src/renderer/src/components/workspace/ai-chat-panel/ai-chat-panel.tsx
  src/renderer/src/components/workspace/ai-chat-panel/chat-input.tsx
  src/renderer/src/components/workspace/ai-chat-panel/typing-loading-animation.tsx
Labels: frontend

#26 [FRT-39] 쿼리 편집기
  src/renderer/src/assets/fonts/JetBrainsMono-Regular.woff2
  src/renderer/src/assets/main.css
  src/renderer/src/components/workspace/ai-chat-panel/chat-message.tsx
  src/renderer/src/components/workspace/query-panel/index.ts
  src/renderer/src/components/workspace/query-panel/query-editor.tsx
  src/renderer/src/components/workspace/query-panel/query-panel.tsx
  src/renderer/src/components/workspace/query-panel/query-results.tsx
  src/renderer/src/components/workspace/workspace.tsx
Labels: frontend

#28 [FRT-55] API 연결
  src/renderer/index.html
  src/renderer/src/components/connection-wizard/confirm-settings.tsx
  src/renderer/src/components/connection-wizard/enter-connection-details.tsx
  src/renderer/src/components/connection-wizard/install-driver.tsx
  src/renderer/src/components/connection-wizard/test-connection.tsx
  src/renderer/src/components/connection-wizard/wizard-modal.tsx
  src/renderer/src/components/connection-wizard/wizard.type.ts
  src/renderer/src/components/setting/key-management.tsx
  src/renderer/src/utils/api.ts
Labels: frontend

#29 [FRT-56] API KEY 관련 에러 해결
  src/renderer/src/components/setting/key-management.tsx
Labels: frontend

#33 [FRT-51] [퍼블리싱] AI 채팅 - 채팅 탭
  src/renderer/src/components/workspace/ai-chat-panel/chat-header.tsx
  src/renderer/src/components/workspace/ai-chat-panel/chat-history-panel.tsx
Labels: publishing

#18 파이프라인 코드 수정
  .github/workflows/build_executables.yaml
  .github/workflows/pr_bot.yml
Labels: infra

#35 [FRT-60] 앱 아이콘 변경
  build/icon.icns
  build/icon.ico
  build/icon.png
  resources/icon.png
Labels: frontend

#31 [FRT-55] API 연결(2)
  src/renderer/src/components/connection-wizard/wizard-modal.tsx
  src/renderer/src/components/erd/table-detail-sidebar.tsx
  src/renderer/src/components/layout/side-bar.tsx
  src/renderer/src/erd/db-schema-panel/annotation-item.tsx
  src/renderer/src/erd/db-schema-panel/annotation-sidebar.tsx
  src/renderer/src/erd/db-schema-panel/annotation.types.ts
  src/renderer/src/erd/erd-page.tsx
  src/renderer/src/erd/erd.type.ts
Labels: frontend

#38 [FRT-59] API 연결 (쿼리 편집, 실행 결과)
  src/main/index.ts
  src/main/ipc/handlers.ts
  src/preload/index.ts
  src/renderer/src/components/workspace/ai-chat-panel/chat-message.tsx
  src/renderer/src/components/workspace/db-schema-panel/db-schema-panel.tsx
  src/renderer/src/components/workspace/query-panel/connection-selector.tsx
  src/renderer/src/components/workspace/query-panel/query-panel.tsx
  src/renderer/src/components/workspace/query-panel/query-results.tsx
  src/renderer/src/components/workspace/workspace.tsx
  src/renderer/src/types/database.ts
Labels: frontend

#40 [FRT-63] 연결된 DB가 없을 때의 화면
  src/main/ipc/handlers.ts
  src/renderer/src/components/connection-wizard/wizard-modal.tsx
  src/renderer/src/components/layout/side-bar.tsx
  src/renderer/src/components/workspace/main-page.tsx
  src/renderer/src/components/workspace/workspace.tsx
Labels: frontend

#41 [FRT-64] 초기 빈 화면 이미지 에셋 추가
  src/renderer/src/assets/empty-image/auto-column-description.png
  src/renderer/src/assets/empty-image/natural-language-query.png
  src/renderer/src/assets/empty-image/query-result.png
  src/renderer/src/components/workspace/feature-card.tsx
  src/renderer/src/components/workspace/types.ts
  src/renderer/src/components/workspace/workspace-empty-state.tsx
Labels: frontend
